# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Collecte terrain en cours'), ('ended', 'Collecte terminée, analyse des données'), ('finalized', 'Collecte finalisée avec documents')], default='started', max_length=50)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('finalized_on', models.DateTimeField(blank=True, null=True)),
                ('commune', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=50)),
                ('nb_submissions', models.IntegerField(blank=True, null=True)),
                ('nb_indigents', models.IntegerField(blank=True, null=True)),
                ('nb_non_indigents', models.IntegerField(blank=True, null=True)),
                ('nb_medias', models.IntegerField(blank=True, null=True)),
                ('medias_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('identifier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('cercle', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('is_indigent', models.NullBooleanField()),
                ('dataset', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamed.Collect')),
            ],
        ),
    ]
