# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import hamed.models.collects


class Migration(migrations.Migration):

    dependencies = [
        ("hamed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="cercle_id",
            field=models.CharField(
                default=hamed.models.collects.default_cercle_id,
                max_length=100,
                verbose_name="Cercle",
            ),
        ),
    ]
