# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamed', '0002_auto_20170203_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='ona_form_pk',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='hamed.Collect'),
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together=set([('commune', 'suffix')]),
        ),
    ]
