# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamed', '0004_auto_20170208_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='ona_scan_form_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
