# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamed', '0005_collect_ona_scan_form_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='medias_size',
            new_name='medias_size_form',
        ),
        migrations.RenameField(
            model_name='collect',
            old_name='nb_medias',
            new_name='nb_medias_form',
        ),
        migrations.AddField(
            model_name='collect',
            name='medias_size_scan_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='nb_medias_scan_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Feminin')], max_length=20),
        ),
    ]
