# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamed', '0006_auto_20170302_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='commune',
            new_name='commune_id',
        ),
        migrations.AddField(
            model_name='collect',
            name='cercle_id',
            field=models.CharField(default='33', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='mayor_name',
            field=models.CharField(default='Maïga Amssetou Touré', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='mayor_title',
            field=models.CharField(choices=[('sir', 'M.'), ('madam', 'Mme'), ('doctor', 'Dr')], default='madam', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together=set([('commune_id', 'suffix')]),
        ),
    ]
