# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamed', '0007_auto_20170304_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'ordering': ['-started_on']},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['key'], 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['-collect__started_on', 'last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='collect',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='cercle_id',
            field=models.CharField(default='33', max_length=100, verbose_name='Cercle'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='commune_id',
            field=models.CharField(max_length=100, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='mayor_name',
            field=models.CharField(max_length=100, verbose_name='Nom du maire'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='mayor_title',
            field=models.CharField(choices=[('sir', 'M.'), ('madam', 'Mme'), ('doctor', 'Dr')], max_length=50, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='suffix',
            field=models.CharField(max_length=50, verbose_name='Suffixe'),
        ),
    ]
